# Generated by Django 4.2.7 on 2024-03-14 10:55

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=257)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('types', multiselectfield.db.fields.MultiSelectField(choices=[('SLEEP_AID', 'SLEEP AID'), ('SLEEP_SNORING', 'SLEEP & SNORING'), ('BREATHING_AIDS', 'BREATHING AIDS'), ('SLEEP_MASKS', 'SLEEP MASKS'), ('LIVING_AIDS', 'LIVING & SAFETY AIDS'), ('HERBAL_SUPPLEMENTS', 'HERBAL_SUPPLEMENTS'), ('VITAMINS', 'VITAMINS')], max_length=100)),
                ('rating', models.CharField(choices=[('One', 'One'), ('two', 'Two'), ('three', 'Three'), ('four', 'Four'), ('five', 'Five')], max_length=10)),
            ],
        ),
    ]
