# Generated by Django 4.2.7 on 2024-03-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0002_category_alter_element_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='types',
        ),
        migrations.AddField(
            model_name='element',
            name='types',
            field=models.ManyToManyField(related_name='categories', to='sleep.category'),
        ),
    ]
