# Generated by Django 4.2.7 on 2024-03-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitems_created_at_cartitems_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='total_sum',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
