# Generated by Django 4.2.7 on 2024-03-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitems_total_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='total_sum',
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
